### PR TITLE
Fix policies leading to Gold cores values being unset

### LINKED ISSUE #20: Gold cores using Performance governor instead of Schedutil
Checking governor for all cores returns:
```bash
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
schedutil
schedutil
schedutil
schedutil
schedutil
schedutil
performance
performance
```
Even though all cores should be set to `schedutil`: https://github.com/sonyxperiadev/device-sony-lena/blob/7345396811b2f096586e846ca2fc6a2630ebd87e/rootdir/vendor/etc/init/init.lena.pwr.rc#L76
So it seems for some reason this setting is not listened to.
I [reported this on their bugtracker already](https://forum.sailfishos.org/t/xperia-10-iii-uses-performance-governor-for-gold-cores-where-it-probably-shouldnt/12695), but I went through Sailfish OS config for Lena and it is not something it changes. So I really think it is not a problem with that OS, but with this setup.

### PR DESCRIPTION
**Pull request by JacekJagosz**
Fixes #20 
Changed `policy4` to `policy6` as well as `min_freq` to `787200`

### CODE REVIEW

**Comment by Thaodan** [comment]
Please also push to r-mr1.

**Comment by JacekJagosz** [comment]
> Please also push to r-mr1.

Why is it necessary if it already is part `s-mr1` and `t-mr1`? What do thos acronyms mean?

**Comment by Thaodan** [comment]
> > Please also push to r-mr1.
> 
> Why is it necessary if it already is part `s-mr1` and `t-mr1`? What do thos
> acronyms mean?

These are the Android Version names besides the version number.

**Comment by Thaodan** [comment]
@jerpelea  Can you do so?

**Comment by jerpelea** [comment]
sure

**Comment by Thaodan** [comment]
the lmk tunings are invalid, they use the values from seine which as less ram.

**Comment by JacekJagosz** [comment]
> the lmk tunings are invalid, they use the values from seine which as less ram.

This is a wrong pull, I think you mean #17 Could you explain it there? I don't see why they are wrong even with less RAM.

**Pull request merged**
